export const VARS = {
    NODE_ENV: "NODE_ENV",
    PORT: "PORT",
    TIME_OUT: "TIME_OUT",
    ORIGIN_CORS: "ORIGIN_CORS",
    REQUEST_RATE_LIMIT: "REQUEST_RATE_LIMIT",
    REQUEST_TIME_TO_LIVE: "REQUEST_TIME_TO_LIVE",
    API_VERSION: "API_VERSION",
    API_PREFIX: "API_PREFIX",
}